//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceToolkit.KSDataSource {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KSDataSource.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetadata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMetadata(string tableKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMetadata", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMetadataAsync(string tableKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSchoolData(string districtID, string townsID, string schoolName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSchoolData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSchoolDataAsync(string districtID, string townsID, string schoolName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAreaData(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAreaDataAsync(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBookData(string Stage, string Grade, string Subject, string Edition, string Booklet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBookDataAsync(string Stage, string Grade, string Subject, string Edition, string Booklet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogkData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCatalogkData(string BookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogkData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCatalogkDataAsync(string BookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResourceTypeChild", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Action))]
        ResourceToolkit.KSDataSource.tb_Template_Tree[] GetResourceTypeChild(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResourceTypeChild", ReplyAction="*")]
        System.Threading.Tasks.Task<ResourceToolkit.KSDataSource.tb_Template_Tree[]> GetResourceTypeChildAsync(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogChild", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Action))]
        ResourceToolkit.KSDataSource.tb_StandardCatalog[] GetCatalogChild(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogChild", ReplyAction="*")]
        System.Threading.Tasks.Task<ResourceToolkit.KSDataSource.tb_StandardCatalog[]> GetCatalogChildAsync(int parentID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tb_Template_Tree : Action {
        
        private System.Nullable<int> idField;
        
        private System.Guid gUIDField;
        
        private string codeNameField;
        
        private System.Nullable<int> seqField;
        
        private System.Nullable<int> parentIDField;
        
        private string pathField;
        
        private System.Nullable<System.DateTime> createDateTimeField;
        
        private System.Nullable<System.DateTime> modifyDateTimeField;
        
        private System.Nullable<int> deletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodeName {
            get {
                return this.codeNameField;
            }
            set {
                this.codeNameField = value;
                this.RaisePropertyChanged("CodeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
                this.RaisePropertyChanged("Seq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
                this.RaisePropertyChanged("ParentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> CreateDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
                this.RaisePropertyChanged("CreateDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> ModifyDateTime {
            get {
                return this.modifyDateTimeField;
            }
            set {
                this.modifyDateTimeField = value;
                this.RaisePropertyChanged("ModifyDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tb_StandardCatalog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tb_Template_Tree))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Action : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tb_StandardCatalog : Action {
        
        private System.Nullable<int> seqField;
        
        private System.Nullable<int> parentIDField;
        
        private System.Nullable<System.DateTime> createDateTimeField;
        
        private System.Nullable<System.DateTime> modifyDateTimeField;
        
        private System.Nullable<int> deletedField;
        
        private int idField;
        
        private System.Nullable<int> bookIDField;
        
        private string folderNameField;
        
        private System.Nullable<int> startPageField;
        
        private System.Nullable<int> endPageField;
        
        private System.Nullable<int> typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> Seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
                this.RaisePropertyChanged("Seq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
                this.RaisePropertyChanged("ParentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> CreateDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
                this.RaisePropertyChanged("CreateDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> ModifyDateTime {
            get {
                return this.modifyDateTimeField;
            }
            set {
                this.modifyDateTimeField = value;
                this.RaisePropertyChanged("ModifyDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> BookID {
            get {
                return this.bookIDField;
            }
            set {
                this.bookIDField = value;
                this.RaisePropertyChanged("BookID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FolderName {
            get {
                return this.folderNameField;
            }
            set {
                this.folderNameField = value;
                this.RaisePropertyChanged("FolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> StartPage {
            get {
                return this.startPageField;
            }
            set {
                this.startPageField = value;
                this.RaisePropertyChanged("StartPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> EndPage {
            get {
                return this.endPageField;
            }
            set {
                this.endPageField = value;
                this.RaisePropertyChanged("EndPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ResourceToolkit.KSDataSource.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ResourceToolkit.KSDataSource.ServiceSoap>, ResourceToolkit.KSDataSource.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMetadata(string tableKey) {
            return base.Channel.GetMetadata(tableKey);
        }
        
        public System.Threading.Tasks.Task<string> GetMetadataAsync(string tableKey) {
            return base.Channel.GetMetadataAsync(tableKey);
        }
        
        public string GetSchoolData(string districtID, string townsID, string schoolName) {
            return base.Channel.GetSchoolData(districtID, townsID, schoolName);
        }
        
        public System.Threading.Tasks.Task<string> GetSchoolDataAsync(string districtID, string townsID, string schoolName) {
            return base.Channel.GetSchoolDataAsync(districtID, townsID, schoolName);
        }
        
        public string GetAreaData(int parentID) {
            return base.Channel.GetAreaData(parentID);
        }
        
        public System.Threading.Tasks.Task<string> GetAreaDataAsync(int parentID) {
            return base.Channel.GetAreaDataAsync(parentID);
        }
        
        public string GetBookData(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            return base.Channel.GetBookData(Stage, Grade, Subject, Edition, Booklet);
        }
        
        public System.Threading.Tasks.Task<string> GetBookDataAsync(string Stage, string Grade, string Subject, string Edition, string Booklet) {
            return base.Channel.GetBookDataAsync(Stage, Grade, Subject, Edition, Booklet);
        }
        
        public string GetCatalogkData(string BookId) {
            return base.Channel.GetCatalogkData(BookId);
        }
        
        public System.Threading.Tasks.Task<string> GetCatalogkDataAsync(string BookId) {
            return base.Channel.GetCatalogkDataAsync(BookId);
        }
        
        public ResourceToolkit.KSDataSource.tb_Template_Tree[] GetResourceTypeChild(int parentID) {
            return base.Channel.GetResourceTypeChild(parentID);
        }
        
        public System.Threading.Tasks.Task<ResourceToolkit.KSDataSource.tb_Template_Tree[]> GetResourceTypeChildAsync(int parentID) {
            return base.Channel.GetResourceTypeChildAsync(parentID);
        }
        
        public ResourceToolkit.KSDataSource.tb_StandardCatalog[] GetCatalogChild(int parentID) {
            return base.Channel.GetCatalogChild(parentID);
        }
        
        public System.Threading.Tasks.Task<ResourceToolkit.KSDataSource.tb_StandardCatalog[]> GetCatalogChildAsync(int parentID) {
            return base.Channel.GetCatalogChildAsync(parentID);
        }
    }
}
